name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
account_id = "dcb5cb4caca718bf2af93c10267ac007"
workers_dev = true
main = "src/worker.js"  # <-- Tambahkan ini

[vars]
TELEGRAM_BOT_TOKEN = "@telegramBotToken"
